[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'


